version: 0.2

phases:
  install:
    commands:
      - echo Installing RSpec...
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Ruby code...
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  base-directory: $CODEBUILD_SRC_DIR
  files:
    - README.md
